# Generated by Django 4.1.13 on 2025-01-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='razorpay_signature',
        ),
    ]
